# Generated by Django 4.2.7 on 2026-01-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
